### ISSUE TITLE
Documentation page is blank

### ISSUE THREAD

**Issue by donmccurdy** [mapbox/shelf-pack#92]
Looking in Firefox and Chrome, the documentation page appears blank: https://mapbox.github.io/shelf-pack/

| screenshot |
|--|
| ![screen shot 2018-12-21 at 12 12 58 am](https://user-images.githubusercontent.com/1848368/50331881-32d62f00-04b5-11e9-9cc2-3e2ec384e719.png) |

**Comment by bhousel** [comment]
hmmm  nope

**Comment by bhousel** [comment]
Actually it is.  GitHub takes a minute.
